// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:890170915182:web:456eaded1c731c814e297f',
    messagingSenderId: '890170915182',
    projectId: 'mha1-9eca0',
    authDomain: 'mha1-9eca0.firebaseapp.com',
    storageBucket: 'mha1-9eca0.firebasestorage.app',
    measurementId: 'G-2V75691J13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:890170915182:android:0f4932275c4850134e297f',
    messagingSenderId: '890170915182',
    projectId: 'mha1-9eca0',
    storageBucket: 'mha1-9eca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:890170915182:ios:458d853974fb0e8c4e297f',
    messagingSenderId: '890170915182',
    projectId: 'mha1-9eca0',
    storageBucket: 'mha1-9eca0.firebasestorage.app',
    iosBundleId: 'com.example.mha1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:890170915182:ios:458d853974fb0e8c4e297f',
    messagingSenderId: '890170915182',
    projectId: 'mha1-9eca0',
    storageBucket: 'mha1-9eca0.firebasestorage.app',
    iosBundleId: 'com.example.mha1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:890170915182:web:876bbb9c0cda2b3b4e297f',
    messagingSenderId: '890170915182',
    projectId: 'mha1-9eca0',
    authDomain: 'mha1-9eca0.firebaseapp.com',
    storageBucket: 'mha1-9eca0.firebasestorage.app',
    measurementId: 'G-H2SZ5MD2DG',
  );

}
